import { Knex } from "knex";
import { users } from "../../src/models";
import { hashPassword } from "../../src/auth/useLocalAuth";

export async function seed(knex: Knex): Promise<void> {
	// Auto-generated by Knex then edited 
	// Deletes ALL existing entries
	await knex("users").del();
	await knex("join_roles_users").del();

	// Inserts seed entries
	await knex("users").insert<users>([
		{
			name: "Kishan",
			auth_type: "oauth",
			email: "jaskishansaran@gmail.com"
		},
		{
			name: "Kishan Local",
			auth_type: "local",
			email: "info@isitweeka.com",
			password: await hashPassword("NotABadPassword")
		}
	]);

	await knex.raw(`
		INSERT INTO join_roles_users (user_id, role_id)
		VALUES (
			(SELECT user_id FROM users WHERE email = 'jaskishansaran@gmail.com'),
			(SELECT role_id FROM roles WHERE path = 'root')
		);
	`);

	await knex.raw(`
		INSERT INTO join_roles_users (user_id, role_id)
		VALUES (
			(SELECT user_id FROM users WHERE email = 'info@isitweeka.com'),
			(SELECT role_id FROM roles WHERE path = 'root')
		);
	`);
}
