import { Knex } from "knex";
import { users } from "../../src/models";
import { hashPassword } from "../../src/auth/useLocalAuth";

export async function seed(knex: Knex): Promise<void> {
	// Auto-generated by Knex then edited 
	// Deletes ALL existing entries
	await knex("users").del();

	// Inserts seed entries
	await knex("users").insert<users>([
		{
			name: "Kishan",
			auth_type: "oauth",
			email: "jaskishansaran@gmail.com"
		},
		{
			name: "Kishan Local",
			auth_type: "local",
			email: "info@isitweeka.com",
			password: await hashPassword("NotABadPassword")
		}
	]);
}
