// @generated
// Automatically generated. Don't change this file manually.

import { competitorsId } from './competitors';
import { competitor_settingsId } from './competitor_settings';

export type competitor_dataId = string & { " __flavor"?: 'competitor_data' };

/**
 * Actual data for competitors, such as how they have performed,, point and any additional data added by points systems (extensions).
 */
export default interface competitor_data {
  /** Primary key. Index: pk_competitor_data */
  competitor_data_id: competitor_dataId;

  /** Index: fkidx_339 */
  competitor_id: competitorsId;

  stored_data: string | null;

  /** Calculated points for this competitor */
  points: string;

  /** Additional data generated by points systems. */
  additional_data: unknown | null;

  /** Set to true if any of points or additional_data have been manually overridden in the GUI. This causes the calculator to skip calculating here. */
  overriden: boolean;

  /**
   * Matches the competitor indirectly back to an event/group via its competitor settings
   * Index: fkidx_350
   */
  competitor_settings_id: competitor_settingsId;

  /** Did not finish - set this to true if the competitor did not finish the event data is being recorded for. */
  dnf: boolean;
}

/**
 * Actual data for competitors, such as how they have performed,, point and any additional data added by points systems (extensions).
 */
export interface competitor_dataInitializer {
  /**
   * Default value: nextval('competitor_data_competitor_data_id_seq'::regclass)
   * Primary key. Index: pk_competitor_data
   */
  competitor_data_id?: competitor_dataId;

  /** Index: fkidx_339 */
  competitor_id: competitorsId;

  stored_data?: string | null;

  /**
   * Calculated points for this competitor
   * Default value: 0
   */
  points?: string;

  /** Additional data generated by points systems. */
  additional_data?: unknown | null;

  /**
   * Set to true if any of points or additional_data have been manually overridden in the GUI. This causes the calculator to skip calculating here.
   * Default value: false
   */
  overriden?: boolean;

  /**
   * Matches the competitor indirectly back to an event/group via its competitor settings
   * Index: fkidx_350
   */
  competitor_settings_id: competitor_settingsId;

  /**
   * Did not finish - set this to true if the competitor did not finish the event data is being recorded for.
   * Default value: false
   */
  dnf?: boolean;
}
