import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
	// Auto-generated by Knex then edited 
	// Deletes ALL existing entries
	await knex("users").del();

	// Inserts seed entries
	await knex("users").insert([
		{
			name: "Kishan",
			auth_type: "oauth",
			email: "jaskishansaran@gmail.com"
		}
	]);
}
