yarnPath: ".yarn/releases/yarn-berry.cjs"
#nodeLinker:
packageExtensions:
  "react-fela@*":
    peerDependencies:
      "fela": "*"
  "@fluentui/utilities@*":
    peerDependencies:
      "react": "*"
  "@fluentui/style-utilities@*":
    peerDependencies:
      "react": "*"
  "@fluentui/font-icons-mdl2@*":
    peerDependencies:
      "react": "*"