/* eslint-disable @typescript-eslint/no-var-requires */
/**
 * Configure Webpack
 * 
 * Most of config taken from https://github.com/2Keys-tech/2Keys-UI (private repo owned by me), which was auto-generated by electron-forge itself
 */

const path = require("path");
const ForkTsCheckerWebpackPlugin = require("fork-ts-checker-webpack-plugin");

module.exports = {
	// Helped by https://webpack.js.org/guides/getting-started/
	entry: "./src/index.tsx",
	output: { // Copied from https://webpack.js.org/guides/getting-started/
		filename: "main.js",
		path: path.join(__dirname, "dist"),
	},
	module: {
		rules: [

			{
				test: /\.tsx?$/,
				exclude: /(node_modules|\.webpack)/,
				use: {
					loader: "ts-loader",
					options: {
						transpileOnly: true,
					}
				}
			},

			{
				test: /\.css$/,
				use: [{ loader: "style-loader" }, { loader: "css-loader" }],
			},

			// From https://webpack.js.org/loaders/sass-loader/
			{
				test: /\.s[ac]ss$/i,
				use: [
					// Creates `style` nodes from JS strings
					"style-loader",
					// Translates CSS into CommonJS
					"css-loader",
					// Compiles Sass to CSS
					"sass-loader",
				],
			},

			{
				test: /\.md$/,
				use: "raw-loader",
			},

			// From https://webpack.js.org/guides/asset-management
			{
				test: /\.(png|svg|jpg|jpeg|gif)$/i,
				type: "asset/resource",
			},
			{
				test: /\.(woff|woff2|eot|ttf|otf)$/i,
				type: "asset/resource",

			},

			
		]
	},

	plugins: [
		new ForkTsCheckerWebpackPlugin(),
	],

	resolve: {
		extensions: [".js", ".ts", ".jsx", ".tsx", ".scss", ".css"],
	},
};